apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
spec:
  {{- if eq .Values.ingressClassName "web-app-routing" }}
  ingressClassName: webapprouting.kubernetes.azure.com
  {{- else if eq .Values.ingressClassName "nginx" }}
  ingressClassName: nginx
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.domain_name }}
      secretName: cert-tls  # Uses your existing TLS secret
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080